### ISSUE TITLE
Request: HID Touchscreen for CH552

### ISSUE THREAD

**Issue by nelsonjchen** [wagiminator/MCU-Templates#3]
I've been using and hacking on https://github.com/biemster/3keys_1knob, a derivative of some of your work on Macropads for some cheap AliExpress keyboards. 

I see that there's an HID mouse example. That is very neat but it only allows relative movements. I'm interested in sending touchscreen commands. There can be certain UIs that aren't friendly to mouses but are to touchscreens. 

I have not been able to hack biemster's 3keys_1knob to the point where the Linux multitouch module is happy. I have been [hacking the files in there](https://github.com/nelsonjchen/3keys_1knob-1/blob/e5f54385c4ad84ad2a470a536d10f3f248c7d2cf/include/usb_descr.c#L94), but I can't say I know exactly what I'm doing. I got it to the point that Linux knows to load multitouch to it but it's still pretty unhappy and `multitouch` in `dmesg` says it "`can't get feature 0`" or whatever that means. Not sure how I'm messing up the report descriptor. 

I see you've been making changes to the templates for CH552. I'm probably going to start from scratch with the updated bases and try again to see if I can make HID Touchscreen "work" at rest without the kernel complaining. 

Anyway, a HID touchscreen example that's compatible with Linux multitouch and possibly Windows 8+ for more users would be very much appreciated!

**Comment by nelsonjchen** [comment]
Arduino prior art:

https://github.com/NicoHood/HID/pull/297/files

**Comment by wagiminator** [comment]
That sounds like an interesting project. Unfortunately, I've never worked with touchscreens before, so I can't help you straight away. The updated templates do not fix any errors or add any new features. They are just slightly optimized and save about 100 bytes of code.

**Comment by nelsonjchen** [comment]
Thanks for your response. I'll continue to keep hacking. If I got something going, I'll be sure to share.

**Comment by wagiminator** [comment]
I'm keeping my fingers crossed for you and I'm looking forward to the result!

**Comment by nelsonjchen** [comment]
I bought a touchscreen off Amazon to compare/steal/capture how it interacts as a touchscreen.

It has a CH554T that talks/makes a touchscreen. Can't find the source though. Hmm.

**Comment by nelsonjchen** [comment]
Possible source. https://github.com/Remychou/usb-touchsreen. Messy, is the license real, but possibly a good reference and it's likely transformative as we're trying to get it to be a cleaner/SDCC implementation here.

**Comment by wagiminator** [comment]
That looks promising.

**Comment by nelsonjchen** [comment]
Just leaving some notes:

My hacking of https://github.com/biemster/3keys_1knob seems to cause an insane amount of USB interrupts after the initial descriptors. I'm probably going to rebase on the latest templates anyway to see if I can get a clean slate. I don't know USB that well but I'm guessing this could cause problems down the line. 

I did hack the biemster/3keys_1knob codebase so that if a HID class setup request comes in, it'll return "I just have 1 finger" with `0x01` and also tried with `0x01, 0x0a` to match the touchscreen. It seemed to cause the interrupts to now fail with `[187843.183682] usb 1-1.3.1: input irq status -75 received` spamming the crap out of `dmesg`. It did this too with a recompiled `https://github.com/biemster/3keys_1knob` but not the blob that's committed to that repo; not sure why. I think maybe I recompiled @biemster's code wrong. Will try again next hacking session.

The touchscreen I got off Amazon doesn't have the same interrupt spam. It has 6 interrupts after the initial setup and response to the max contact request and then it immediately quiets down. Of course, I'm not exactly sure what its codebase does either. 

I don't know USB that well so I'm guessing it's something in the descriptor or even other descriptors that can cause this spam. I'm going to stare at more Wireshark and keep experimenting. 

My plan is currently this:

1. Replace the descriptor with one similar to the Amazon touchscreen, but with 1 finger.
2. Implement a response for "what's your max contact count" to 1.
3. Try to send a touch at 100,100 and see if `libinput debug-events` sees it. 


OK those are my notes. Will keep posting if there's anything. My setup isn't the greatest. I VSCcde remote to a Raspberry Pi 3 and the 1GB of RAM and the very disable happy USB hub make it a bit tight and frustrating.

**Comment by nelsonjchen** [comment]
Bah the GitHub reply displayed twice in GitHub mobile and I accidentally deleted it.

Anyway, quick summary is the hacking I've been doing seems to cause interrupt troubles. Will rebase to the template to try to sort it out.

Also, not sure if my compilation environment is making something that causes this as well.

**Comment by nelsonjchen** [comment]
Haven't had much success. Life has been busy but what time I've had with it hasn't been too great. I've decided to go and rebase atop the newest templates and do a hello world with a mouse jiggler on my setup to make sure I can even send reports if necessary. 

I can get the LED on my development board to blink, that's great. However, any calls to mouse_move afterwards seem to cause the board to lock up or something. Extremely, extremely frustrating. I'm not sure if it's an issue with SDCC either.

**Comment by nelsonjchen** [comment]
It took me forever, especially with life stuff, but i have a small hardcoded hello world going now. 😁 

https://github.com/nelsonjchen/ch552-touch-play 

It touches on a loop. 

I need to get my use case going first and foremost and then look to see how to extract it out to a nice PR to this repo someday.

**Comment by nelsonjchen** [comment]
https://github.com/wagiminator/MCU-Templates/assets/5363/e9416470-748a-424c-a64b-48dd8ea15d02

Hardcoded use case so far so good 😄

**Comment by wagiminator** [comment]
Great!!!

**Comment by nelsonjchen** [comment]
Works for my use case with the comma three. But not my girlfriend's Windows laptop after going to 2 fingers and above for some reason.

Will continue to polish and hopefully PR a working Windows compatible template implementation.

https://youtube.com/shorts/-VjC_3XHyv0?si=vSlsnMmhSsbk-Hsw

**Comment by nelsonjchen** [comment]
"Productized" repo out. 

https://github.com/nelsonjchen/c3-touchkey-keyboard

**Comment by wagiminator** [comment]
Fantastic, this really turned out to be a cool project. Congratulations!!!

**Comment by nelsonjchen** [comment]
Thanks! You and @biemster were the real MVPs!

**Comment by nelsonjchen** [comment]
https://github.com/nelsonjchen/c3-faux-touch-keyboard/releases/tag/0.0.4 released with a refactor candidate/test for future upstreaming. Am traveling next week for the following two weeks. 

Will probably go for MVP with the API for now for upstreaming when back
